### ISSUE TITLE
怎样添加FPN到faster rcnn中

### ISSUE THREAD

**Issue by zqdeepbluesky** [gyxoned/pytorch-FPN#2]
你好，我想把FPN添加到faster rcnn中去，但是我不是很清楚应该修改faster rcnn的哪些内容，你能告诉我应该怎么修改吗，万分感谢！

**Comment by yxgeee** [comment]
Actually, I have finished FPN, and you can run it by the script as below.
[https://github.com/gyxoned/pytorch-FPN/blob/master/experiments/scripts/train_faster_rcnn_fpn.sh](url)

But, the multi-gpu version hasn't been finished.

**Comment by zqdeepbluesky** [comment]
ok,I will Implementation it ,thanks so much.
