### ISSUE TITLE
关于新建工程

### ISSUE THREAD

**Issue by jacktkk** [gyxoned/pytorch-FPN#4]
您好，好像您这个工程是自己新建的，而不是直接从ruotianluo那里fork过来的。因为我看您的branch中只有两条分支，所以我猜测这个工程应该您自己新建的吧？
请问这种不需要fork但又能加载其他开源工程的做法是怎么实现的？

**Comment by yxgeee** [comment]
git clone the origin repository to your local directory, and then git push to a new empty repository.

**Comment by jacktkk** [comment]
thx a lot
